name: Android CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.2.0
        with:
          project-path: /home/runner/work/CryptoApp/CryptoApp
          output-path: crypto-app-test.apk

